const webs = [
    {'id': 0,
    'name':'Ephemerigames',
    'url':'https://ephemerigames.vercel.app/', 
    'github':'https://github.com/MaxiAlem/ephemerigames',
    },
    {'id': 1,
    'name':'VirtualCheems',
    'url':'https://inquisitive-concha-76fed7.netlify.app/', 
    'github':'https://github.com/MaxiAlem/cheems-virtual',
    },
    {'id': 2,
    'name':'State your Might',
    'url':'https://gorgeous-beijinho-59fdba.netlify.app/', 
    'github':'https://github.com/MaxiAlem/state-your-might',
    },
    {'id': 3,
    'name':'Pokemon Quiz',
    'url':'https://timely-torrone-68fc68.netlify.app/', 
    'github':'https://github.com/MaxiAlem/whos-that-pokemon-challenge',
    },
]

const skills =[
    {'name':'html5',
    'src':'../assets/html5.png',
    'lvl':75},
    {'name':'css3',
    'src':'../assets/css3.png',
    'lvl':''},
    {'name':'js',
    'src':'../assets/js.png',
    'lvl':''},
    {'name':'react',
    'src':'../assets/react.png',
    'lvl':''},
    {'name':'bootstrap',
    'src':'../assets/bootstrap.png',
    'lvl':''},
    {'name':'node',
    'src':'../assets/node.png',
    'lvl':''},
    {'name':'mongo',
    'src':'../assets/mongo.png',
    'lvl':''},
    {'name':'python',
    'src':'../assets/python.png',
    'lvl':''},

]

export {webs, skills}